#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# Set up monitors
~/.config/bspwm/monitor_setup.sh

bspc monitor -d I II III IV V VI VII VIII IX X

# Start MPD service
systemctl --user start mpd

# polybar
~/.config/polybar/launch.sh --forest

# Set the background image
~/.config/bspwm/set_background.sh

# Start Kitty terminal
kitty &

# Start Picom
picom --config ~/.config/picom/picom.conf &

# corner radius
# ~/.config/bspwm/corner_radius.sh

compton --backend glx --vsync opengl-swc &

nitrogen --restore &

bspc config border_width 2
bspc config window_gap 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set border width
# bspc config border_width 2

# Set outer padding (optional)
#bspc config top_padding 10
#bspc config bottom_padding 10
#bspc config left_padding 10
#bspc config right_padding 10
